// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RzVv2zKUTMYulvb3LIpki7zyJF1Ur7w',
    appId: '1:896934377892:android:8ec741dd42a23c59362931',
    messagingSenderId: '896934377892',
    projectId: 'nxbvotingapp',
    databaseURL: 'https://nxbvotingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nxbvotingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSOB1UxOkPLnt701Lna2uQy-eWGQGUxdE',
    appId: '1:896934377892:ios:650440e234173278362931',
    messagingSenderId: '896934377892',
    projectId: 'nxbvotingapp',
    databaseURL: 'https://nxbvotingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nxbvotingapp.appspot.com',
    iosBundleId: 'com.berriesecomstore.berriesecomstore',
  );
}
