// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0NJHtpPxtDWje4B64DKT9zAiDmqnUMU',
    appId: '1:1054623071585:web:5bfaa6f124d1e2747e5920',
    messagingSenderId: '1054623071585',
    projectId: 'ecomlenz-1bb68',
    authDomain: 'ecomlenz-1bb68.firebaseapp.com',
    storageBucket: 'ecomlenz-1bb68.firebasestorage.app',
    measurementId: 'G-SJT8HD8HRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUS-kYTl0GfEOWJ5eL6R9j3e_4evT0X4',
    appId: '1:1054623071585:android:57f9863bf51b1d537e5920',
    messagingSenderId: '1054623071585',
    projectId: 'ecomlenz-1bb68',
    storageBucket: 'ecomlenz-1bb68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTTLpbGswWN9WmCNbW0p8gjcbmoUNzZxk',
    appId: '1:1054623071585:ios:d60b979316752e0a7e5920',
    messagingSenderId: '1054623071585',
    projectId: 'ecomlenz-1bb68',
    storageBucket: 'ecomlenz-1bb68.firebasestorage.app',
    iosBundleId: 'com.ecomlenz.ecomlenz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_0NJHtpPxtDWje4B64DKT9zAiDmqnUMU',
    appId: '1:1054623071585:web:a9eb2f425822a6267e5920',
    messagingSenderId: '1054623071585',
    projectId: 'ecomlenz-1bb68',
    authDomain: 'ecomlenz-1bb68.firebaseapp.com',
    storageBucket: 'ecomlenz-1bb68.firebasestorage.app',
    measurementId: 'G-4KJ49697XF',
  );
}
